
name: test-hgcal

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python pip install .
        python pytest pytest-dependency

    - name: Test with pytest
      run: |
        python3 -m pytest tests/test_execution.py -m "hgcal" 